name: git-scrape
on:
  schedule:
    - cron: "*/15 * * * *"    # every 15 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install requests beautifulsoup4 pyyaml
      - run: python scrape.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || (git commit -m "Snapshot update" && git push)

